version: '3'

services:
  #DB用コンテナ
  db:
    container_name: voting-app-php-db
    image: mysql:5.7
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 8081:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root

  #app用コンテナ
  public:
    container_name: voting-app-php-public
    build: ./php
    volumes:
      - ./public:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - db
