version: '3'

services:
  #MySQL用コンテナ
  mysql:
    container_name: voting-app-php-mysql
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 8081:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test

  #phpMyAdmin用コンテナ
  # phpmyadmin:
  #   container_name: voting-app-php-phpMyAdmin
  #   depends_on:
  #     - mysql
  #   image: phpmyadmin/phpmyadmin
  #   environment:
  #     PMA_HOST: mysql
  #   restart: always
  #   ports:
  #     - 8082:80

  #php用コンテナ
  php:
    container_name: voting-app-php-apache
    build: ./php
    volumes:
      - ./html:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - mysql
